version: "3.9"
   
services:
  db:
    build: /database
    image: amdaris/fhirbase
    ports:
      - "3000:3000"
      - "5432:5432"
  backend:
    build: /backend
    image: amdaris/backend-spring
    ports:
      - "8080:8080"
    depends_on:
      - db
  frontend:
    build: /frontend
    image: amdaris/frontend-angular
    ports:
      - "4200:80"
    depends_on:
      - db,
      - backend